package com.iwe.avenger.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Avenger")
public class Avenger {

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBIndexHashKey(attributeName="HeroName", globalSecondaryIndexName="HeroName-index")
	private String name;
	
	@DynamoDBAttribute(attributeName="SecretIdentity")
	private String secretIdentity;

	public Avenger() {
		super();
	}

	public Avenger(String id, String name, String secretIdentity) {
		super();
		this.id = id;
		this.name = name;
		this.secretIdentity = secretIdentity;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSecretIdentity() {
		return secretIdentity;
	}

	public void setSecretIdentity(String secretIdentity) {
		this.secretIdentity = secretIdentity;
	}

}
